apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Android Build and Security Scan

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  trigger-jenkins-build:
    steps:
      - name: Trigger Jenkins Android Pipeline
        id: jenkins-build
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          url: https://core.cloudbees.guru/shared-demos/
          username: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job-name: lsa/Workspace-Caching/2048
          parameters: |
            {
              "CLEAN_BUILD": "false",
              "BUILD_TYPE": "release"
            }
          
      - name: Extract APK download URL from Jenkins output
        id: extract-apk-url
        uses: docker://alpine:latest
        env:
          JENKINS_OUTPUT: ${{ steps.jenkins-build.outputs.jenkins_output }}
        run: |
          echo "🔍 Analyzing Jenkins output for APK URL..."
          
          # Install required tools
          apk add --no-cache grep
          
          # Print Jenkins output for debugging
          echo "Jenkins Output:"
          echo "$JENKINS_OUTPUT"
          
          # Try to extract APK URL from the Jenkins output
          APK_URL=$(echo "$JENKINS_OUTPUT" | grep -o 'https://bashupload.com/[^[:space:]]*' | head -1)
          
          if [ -n "$APK_URL" ]; then
            echo "✅ Found APK URL: $APK_URL"
            echo "$APK_URL" >> "$CLOUDBEES_OUTPUTS/APK_URL"
          else
            echo "❌ No APK URL found in Jenkins output"
            echo "Trying alternative patterns..."
            
            # Try different patterns for bashupload URLs
            APK_URL=$(echo "$JENKINS_OUTPUT" | grep -i "bashupload" | grep -o 'https://[^[:space:]]*' | head -1)
            
            if [ -n "$APK_URL" ]; then
              echo "✅ Found alternative APK URL: $APK_URL"
              echo "$APK_URL" >> "$CLOUDBEES_OUTPUTS/APK_URL"
            else
              echo "NONE" >> "$CLOUDBEES_OUTPUTS/APK_URL"
            fi
          fi

    outputs:
      BUILD_STATUS: ${{ steps.jenkins-build.outputs.jenkins_output }}
      APK_URL: ${{ steps.extract-apk-url.outputs.APK_URL }}

  security-scan:
    needs: trigger-jenkins-build
    steps:
      - name: Checkout source code
        uses: cloudbees-io/checkout@v1
        
      - name: Security scan with SonarQube
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        kind: scan
        continue-on-error: true
        with:
          language: LANGUAGE_JAVA
          
      - name: Security scan with Snyk
        uses: cloudbees-io/snyk-sast-scan-code@v1
        kind: scan
        continue-on-error: true
        with:
          orgname: ${{ secrets.SNYK_ORGNAME }}
          token: ${{ secrets.SNYK_TOKEN }}
          language: LANGUAGE_JAVA
          
      - name: Publish security results
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Security Scan Results
            
            Security scanning has been performed on the Java/Android source code.
            Check the security tabs to see detailed vulnerability findings.
          format: MARKDOWN

  binary-security-scan:
    needs: trigger-jenkins-build
    if: ${{ success() && needs.trigger-jenkins-build.outputs.APK_URL != 'NONE' }}
    steps:
      - name: Download and scan APK
        uses: docker://alpine:latest
        env:
          APK_URL: ${{ needs.trigger-jenkins-build.outputs.APK_URL }}
        run: |
          echo "🔍 Downloading APK from: $APK_URL"
          
          # Install required tools
          apk add --no-cache wget file
          
          # Download the APK
          if wget -O app.apk "$APK_URL"; then
            echo "✅ APK downloaded successfully"
            
            # Verify it's actually an APK file
            file app.apk
            
            # Check file size
            APK_SIZE=$(stat -c%s app.apk)
            echo "APK Size: ${APK_SIZE} bytes"
            
            # Basic APK security checks
            echo "📱 Basic APK security analysis..."
            
            # Check if it's a valid ZIP archive (APK format)
            if file app.apk | grep -q "Zip archive"; then
              echo "✅ Valid APK format detected"
            else
              echo "⚠️ Warning: File may not be a valid APK"
            fi
            
            echo "✅ APK security scan completed"
          else
            echo "❌ Failed to download APK from $APK_URL"
            exit 1
          fi
          
      - name: Publish APK scan results
        uses: cloudbees-io/publish-evidence-item@v1
        if: always()
        with:
          content: |-
            ## Android APK Security Scan
            
            **APK Download URL**: ${{ needs.trigger-jenkins-build.outputs.APK_URL }}
            
            The APK file generated by the Jenkins pipeline has been downloaded and analyzed.
            
            ### Security Checks Performed:
            - ✅ File format validation
            - ✅ File size verification
            - ✅ Basic integrity checks
            
            ### Recommendations for Enhanced Security:
            For comprehensive mobile security scanning, consider integrating:
            - **MobSF** (Mobile Security Framework)
            - **QARK** (Quick Android Review Kit) 
            - **Veracode** mobile scanning
            - **Checkmarx** mobile analysis
            
            Current scan completed successfully with basic validation.
          format: MARKDOWN