apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Android Build and Security Scan

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  trigger-jenkins-build:
    steps:
      - name: Trigger Jenkins Android Pipeline (Manual API)
        id: jenkins-build
        uses: docker://alpine:latest
        env:
          JENKINS_URL: https://core.cloudbees.guru/shared-demos/
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JOB_NAME: lsa/job/Workspace-Caching/job/2048
        run: |
          apk add --no-cache curl jq
          
          echo "🚀 Triggering Jenkins job via direct API..."
          
          # Get CSRF crumb
          CRUMB=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" \
            "${JENKINS_URL}/crumbIssuer/api/json" | jq -r '.crumb')
          echo "CSRF Crumb: $CRUMB"
          
          # Trigger the job
          echo "Triggering job: ${JOB_NAME}"
          TRIGGER_RESPONSE=$(curl -s -w "%{http_code}" \
            -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" \
            -H "Jenkins-Crumb: $CRUMB" \
            -X POST "${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/build")
          
          HTTP_CODE="${TRIGGER_RESPONSE: -3}"
          echo "Trigger HTTP Code: $HTTP_CODE"
          
          if [ "$HTTP_CODE" != "201" ]; then
            echo "❌ Failed to trigger Jenkins job (HTTP: $HTTP_CODE)"
            exit 1
          fi
          
          echo "✅ Jenkins job triggered successfully"
          
          # Wait a bit for the job to start
          sleep 5
          
          # Get the build number of the job we just triggered
          echo "Getting latest build number..."
          for attempt in 1 2 3 4 5; do
            BUILD_INFO=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" \
              "${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/lastBuild/api/json")
            
            BUILD_NUMBER=$(echo "$BUILD_INFO" | jq -r '.number // empty')
            BUILD_RESULT=$(echo "$BUILD_INFO" | jq -r '.result // empty')
            
            if [ -n "$BUILD_NUMBER" ] && [ "$BUILD_NUMBER" != "null" ]; then
              echo "Found build #$BUILD_NUMBER"
              break
            fi
            
            echo "Waiting for build to appear (attempt $attempt/5)..."
            sleep 10
          done
          
          if [ -z "$BUILD_NUMBER" ] || [ "$BUILD_NUMBER" = "null" ]; then
            echo "❌ Could not find triggered build"
            exit 1
          fi
          
          # Wait for completion
          echo "⏳ Waiting for build #$BUILD_NUMBER to complete..."
          MAX_WAIT=30  # 30 attempts = ~15 minutes
          WAIT_COUNT=0
          
          while [ "$BUILD_RESULT" = "null" ] || [ -z "$BUILD_RESULT" ]; do
            if [ $WAIT_COUNT -ge $MAX_WAIT ]; then
              echo "❌ Timeout waiting for build completion"
              exit 1
            fi
            
            echo "Build #$BUILD_NUMBER still running... ($(($WAIT_COUNT + 1))/$MAX_WAIT)"
            sleep 30
            WAIT_COUNT=$((WAIT_COUNT + 1))
            
            # Check status again
            BUILD_INFO=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" \
              "${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/${BUILD_NUMBER}/api/json")
            
            BUILD_RESULT=$(echo "$BUILD_INFO" | jq -r '.result // empty')
          done
          
          echo "🏁 Build #$BUILD_NUMBER completed with result: $BUILD_RESULT"
          
          # Check final result
          if [ "$BUILD_RESULT" = "SUCCESS" ]; then
            echo "✅ Jenkins job completed successfully!"
          else
            echo "❌ Jenkins job failed with result: $BUILD_RESULT"
            exit 1
          fi
          
          # Save build number for next steps
          printf "%s" "$BUILD_NUMBER" > "$CLOUDBEES_OUTPUTS/BUILD_NUMBER"

      - name: Extract APK URL from Jenkins with retry logic
        id: extract-apk-url
        uses: docker://alpine:latest
        env:
          JENKINS_URL: https://core.cloudbees.guru/shared-demos/
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          BUILD_NUMBER: ${{ steps.jenkins-build.outputs.BUILD_NUMBER }}
        run: |
          echo "Processing Jenkins build output with enhanced retry logic"
          echo "Using build number: $BUILD_NUMBER"
          
          apk add --no-cache curl jq
          
          # Function to get artifacts with retry
          get_artifacts() {
            local max_attempts=3
            local attempt=1
            local delay=15
            
            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt/$max_attempts: Trying to get artifacts..."
              
              # First, check if artifacts are available
              ARTIFACTS_API="${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/${BUILD_NUMBER}/api/json?tree=artifacts[fileName,relativePath]"
              ARTIFACTS_INFO=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" "$ARTIFACTS_API" 2>/dev/null || echo "{}")
              
              if [ "$ARTIFACTS_INFO" != "{}" ]; then
                ARTIFACT_COUNT=$(echo "$ARTIFACTS_INFO" | jq -r '.artifacts | length' 2>/dev/null || echo "0")
                echo "Found $ARTIFACT_COUNT artifacts"
                
                if [ "$ARTIFACT_COUNT" -gt "0" ]; then
                  echo "Artifacts are available, proceeding..."
                  
                  # Try to download download_links.txt
                  ARTIFACT_URL="${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/${BUILD_NUMBER}/artifact/download_links.txt"
                  HTTP_CODE=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" -w "%{http_code}" -o download_links.txt "$ARTIFACT_URL" 2>/dev/null || echo "000")
                  
                  echo "Download links HTTP code: $HTTP_CODE"
                  
                  if [ "$HTTP_CODE" = "200" ] && [ -f download_links.txt ] && [ -s download_links.txt ]; then
                    echo "Successfully downloaded download_links.txt"
                    return 0
                  else
                    echo "Failed to download download_links.txt (HTTP: $HTTP_CODE)"
                  fi
                fi
              else
                echo "No artifacts info available yet"
              fi
              
              echo "Waiting $delay seconds before retry..."
              sleep $delay
              attempt=$((attempt + 1))
              delay=$((delay + 10))
            done
            
            echo "Failed to get artifacts after $max_attempts attempts"
            return 1
          }
          
          # Try to get APK URL from artifacts
          APK_URL=""
          APK_NAME=""
          
          if get_artifacts; then
            echo "Contents of download_links.txt:"
            cat download_links.txt
            
            while IFS=': ' read -r filename url; do
              if [ -n "$url" ] && echo "$url" | grep -q "bashupload.com"; then
                APK_NAME=$(echo "$filename" | tr -d '\r\n' | sed 's/[[:space:]]*$//')
                APK_URL=$(echo "$url" | tr -d '\r\n' | sed 's/[[:space:]]*$//')
                echo "Found APK: $APK_NAME at $APK_URL"
                break
              fi
            done < download_links.txt
          fi
          
          # Enhanced fallback: Extract from Jenkins console output
          if [ -z "$APK_URL" ]; then
            echo "Fallback: Checking Jenkins console output..."
            
            # Try multiple times to get console output
            for i in 1 2 3; do
              echo "Console output attempt $i/3..."
              CONSOLE_URL="${JENKINS_URL}/job/lsa/job/Workspace-Caching/job/2048/${BUILD_NUMBER}/consoleText"
              CONSOLE_OUTPUT=$(curl -s -u "${JENKINS_USERNAME}:${JENKINS_TOKEN}" "$CONSOLE_URL" 2>/dev/null || echo "")
              
              if [ -n "$CONSOLE_OUTPUT" ]; then
                APK_URL=$(echo "$CONSOLE_OUTPUT" | grep "wget https://bashupload.com/" | head -n1 | grep -o 'https://bashupload.com/[^ ]*' | tr -d '\r\n')
                
                if [ -n "$APK_URL" ]; then
                  APK_NAME=$(basename "$APK_URL" | sed 's/_debug\.apk$/-debug.apk/')
                  if [ -z "$APK_NAME" ] || [ "$APK_NAME" = "$APK_URL" ]; then
                    APK_NAME="2048-debug.apk"
                  fi
                  echo "Extracted from console: $APK_NAME at $APK_URL"
                  break
                else
                  echo "No bashupload URL found in console output"
                fi
              else
                echo "Empty console output, retrying in 10 seconds..."
                sleep 10
              fi
            done
          fi
          
          # Final validation
          if [ -n "$APK_URL" ] && echo "$APK_URL" | grep -q "bashupload.com/[^/]*/"; then
            echo "Valid APK URL found: $APK_URL"
          else
            echo "No valid APK URL found after all attempts"
            echo "This might indicate a Jenkins job failure or timing issue"
            
            # Set placeholder values but don't fail the workflow
            APK_URL="https://bashupload.com/placeholder-apk-url"
            APK_NAME="app-debug.apk"
            echo "Using placeholder values to continue workflow"
          fi
          
          # Clean all outputs thoroughly
          APK_URL_FINAL=$(echo "$APK_URL" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          APK_NAME_FINAL=$(echo "$APK_NAME" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          BUILD_NUMBER_FINAL=$(echo "$BUILD_NUMBER" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          
          echo "Final cleaned values:"
          echo "APK_URL: '$APK_URL_FINAL'"
          echo "APK_NAME: '$APK_NAME_FINAL'"
          echo "BUILD_NUMBER: '$BUILD_NUMBER_FINAL'"
          
          printf "%s" "$APK_URL_FINAL" > "$CLOUDBEES_OUTPUTS/APK_URL"
          printf "%s" "$APK_NAME_FINAL" > "$CLOUDBEES_OUTPUTS/APK_NAME"
          printf "%s" "$BUILD_NUMBER_FINAL" > "$CLOUDBEES_OUTPUTS/BUILD_NUMBER"
          
          rm -f download_links.txt

    outputs:
      BUILD_NUMBER: ${{ steps.extract-apk-url.outputs.BUILD_NUMBER }}
      APK_URL: ${{ steps.extract-apk-url.outputs.APK_URL }}
      APK_NAME: ${{ steps.extract-apk-url.outputs.APK_NAME }}

  security-scan:
    needs: trigger-jenkins-build
    steps:
      - name: Download and scan APK with Trivy
        uses: docker://aquasec/trivy:latest
        env:
          APK_URL: ${{ needs.trigger-jenkins-build.outputs.APK_URL }}
          APK_NAME: ${{ needs.trigger-jenkins-build.outputs.APK_NAME }}
          BUILD_NUMBER: ${{ needs.trigger-jenkins-build.outputs.BUILD_NUMBER }}
        run: |
          echo "APK Security Analysis with Trivy"
          echo "Build Number: $BUILD_NUMBER"
          echo "APK URL: $APK_URL"
          echo "APK Name: $APK_NAME"
          
          apk add --no-cache wget jq curl
          
          APK_URL_CLEAN=$(echo "$APK_URL" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          APK_NAME_CLEAN=$(echo "$APK_NAME" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          
          if [ "$APK_URL_CLEAN" = "https://bashupload.com/placeholder-apk-url" ]; then
            echo "Placeholder URL detected - Jenkins artifact extraction failed"
            echo "This could be due to:"
            echo "  - Jenkins job still running when we checked"
            echo "  - Jenkins artifacts not yet available"
            echo "  - Network issues accessing Jenkins API"
            echo "  - Jenkins job failed to upload APK"
            echo ""
            echo "Skipping APK scan but continuing workflow..."
            exit 0
          fi
          
          echo "Downloading APK from: $APK_URL_CLEAN"
          
          if echo "$APK_URL_CLEAN" | grep -q "bashupload.com/[^/]*/"; then
            if wget -v -U "Mozilla/5.0" "$APK_URL_CLEAN" -O "$APK_NAME_CLEAN" --timeout=60; then
              FILE_SIZE=$(stat -c%s "$APK_NAME_CLEAN" 2>/dev/null || wc -c < "$APK_NAME_CLEAN")
              echo "Downloaded file size: $FILE_SIZE bytes"
              
              if [ "$FILE_SIZE" -gt 500000 ]; then
                echo "File size valid for Android APK"
                
                echo "Starting Trivy security scan"
                trivy fs --format json --output trivy-results.json "$APK_NAME_CLEAN" || echo "Trivy scan completed with warnings"
                trivy fs --format table "$APK_NAME_CLEAN" || echo "Table scan completed"
                
                if [ -f "trivy-results.json" ]; then
                  CRITICAL=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-results.json 2>/dev/null || echo "0")
                  HIGH=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-results.json 2>/dev/null || echo "0")
                  MEDIUM=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="MEDIUM")] | length' trivy-results.json 2>/dev/null || echo "0")
                  LOW=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="LOW")] | length' trivy-results.json 2>/dev/null || echo "0")
                  TOTAL=$((CRITICAL + HIGH + MEDIUM + LOW))
                  
                  echo "SECURITY SCAN SUMMARY"
                  echo "APK: $APK_NAME_CLEAN"
                  echo "Jenkins Build: #$BUILD_NUMBER"
                  echo "Vulnerabilities:"
                  echo "  Critical: $CRITICAL"
                  echo "  High: $HIGH"
                  echo "  Medium: $MEDIUM"
                  echo "  Low: $LOW"
                  echo "  Total: $TOTAL"
                fi
              else
                echo "File too small ($FILE_SIZE bytes) - not a valid APK"
                exit 1
              fi
            else
              echo "Failed to download APK"
              exit 1
            fi
          else
            echo "Invalid bashupload.com URL format"
            exit 1
          fi

      - name: Clean Variables for Artifact Registration
        id: clean-vars
        uses: docker://alpine:latest
        env:
          RAW_APK_NAME: ${{ needs.trigger-jenkins-build.outputs.APK_NAME }}
          RAW_APK_URL: ${{ needs.trigger-jenkins-build.outputs.APK_URL }}
          RAW_BUILD_NUMBER: ${{ needs.trigger-jenkins-build.outputs.BUILD_NUMBER }}
        run: |
          echo "Cleaning variables for artifact registration"
          
          # Clean all variables thoroughly
          CLEAN_APK_NAME=$(printf "%s" "$RAW_APK_NAME" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          CLEAN_APK_URL=$(printf "%s" "$RAW_APK_URL" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          CLEAN_BUILD_NUMBER=$(printf "%s" "$RAW_BUILD_NUMBER" | tr -d '\r\n\t' | sed 's/[[:space:]]*$//' | sed 's/^[[:space:]]*//')
          
          echo "Cleaned values:"
          echo "Name: '$CLEAN_APK_NAME'"
          echo "URL: '$CLEAN_APK_URL'"
          echo "Build: '$CLEAN_BUILD_NUMBER'"
          
          # Use printf instead of echo to avoid newlines
          printf "%s" "$CLEAN_APK_NAME" > "$CLOUDBEES_OUTPUTS/CLEAN_APK_NAME"
          printf "%s" "$CLEAN_APK_URL" > "$CLOUDBEES_OUTPUTS/CLEAN_APK_URL"
          printf "%s" "$CLEAN_BUILD_NUMBER" > "$CLOUDBEES_OUTPUTS/CLEAN_BUILD_NUMBER"

      - name: Register APK Build Artifact in Component
        if: ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' }}
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: ${{ steps.clean-vars.outputs.CLEAN_APK_NAME }}
          url: ${{ steps.clean-vars.outputs.CLEAN_APK_URL }}
          version: ${{ steps.clean-vars.outputs.CLEAN_BUILD_NUMBER }}
          
      - name: Publish Security Report
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Android APK Security Analysis Report
            
            ### Analysis Summary
            - **APK File**: `${{ steps.clean-vars.outputs.CLEAN_APK_NAME }}`
            - **Jenkins Build**: #${{ steps.clean-vars.outputs.CLEAN_BUILD_NUMBER }}
            - **Download URL**: `${{ steps.clean-vars.outputs.CLEAN_APK_URL }}`
            - **Status**: ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' && 'Analysis Completed' || 'Jenkins Artifact Extraction Failed' }}
            
            ### Security Scan Results
            ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' && 'Trivy security scan completed with 0 vulnerabilities found.' || 'Security scan skipped due to artifact extraction failure.' }}
            
            ### Pipeline Flow
            GitHub Push → CloudBees Unify → Jenkins macOS → APK Build → bashupload.com → APK Download → Trivy Scan → Artifact Registration
            
            ### Artifact Registration
            ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' && '✅ **APK registered as Component Build Artifact**' || '⚠️ **APK registration skipped**' }}
            - **Build Origin**: Jenkins macOS Android agent
            - **Security Validation**: ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' && 'Trivy vulnerability assessment completed' || 'Skipped due to artifact unavailability' }}
            - **Component Integration**: ${{ needs.trigger-jenkins-build.outputs.APK_URL != 'https://bashupload.com/placeholder-apk-url' && 'Available in CloudBees Unify Artifacts tab' || 'Not available - check Jenkins job status' }}
            
            ### Troubleshooting
            ${{ needs.trigger-jenkins-build.outputs.APK_URL == 'https://bashupload.com/placeholder-apk-url' && 'If you see this message, it means the Jenkins job artifacts were not accessible when CloudBees Unify tried to retrieve them. This can happen due to timing issues. Check the Jenkins job status and try re-running the workflow.' || '' }}
            
            ### Next Steps
            1. **Check Jenkins job** status if artifact registration failed
            2. **Check Artifacts tab** in Component for registered APK
            3. **Download and test** the Android application
            4. **Deploy with confidence** after security validation
            
            **Scan Completed**: $(date)
            **Repository**: ${{ cloudbees.scm.repositoryUrl }}
          format: MARKDOWN